#!/bin/bash
# Email configuration helper for Gmail

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║        Gmail App Password Setup for Sportivity           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "To receive email notifications, you need a Gmail App Password."
echo ""
echo "📋 STEPS:"
echo ""
echo "1. Go to: https://myaccount.google.com/apppasswords"
echo "   (You'll be asked to sign in to your Google account)"
echo ""
echo "2. If you see 'App passwords' unavailable:"
echo "   - First enable 2-Step Verification at:"
echo "     https://myaccount.google.com/signinoptions/two-step-verification"
echo "   - Then return to step 1"
echo ""
echo "3. On the App passwords page:"
echo "   - Select app: 'Mail'"
echo "   - Select device: 'Mac' (or your device)"
echo "   - Click 'Generate'"
echo ""
echo "4. Copy the 16-character password (format: xxxx xxxx xxxx xxxx)"
echo ""
echo "5. Update your .env file with:"
echo "   EMAIL_SMTP_PASSWORD=your_16_char_password_without_spaces"
echo ""
echo "6. Test it:"
echo "   python3 test_email.py"
echo ""
echo "❓ TROUBLESHOOTING:"
echo ""
echo "Can't find App passwords?"
echo "  → Make sure 2-Step Verification is ON"
echo "  → Use the direct link above"
echo ""
echo "Email not sending?"
echo "  → Check .env has correct EMAIL_FROM and EMAIL_TO"
echo "  → Verify ENABLE_EMAIL=true"
echo "  → Remove spaces from app password"
echo "  → Check logs: grep 'email' anytime_booking.log"
echo ""
echo "Still stuck?"
echo "  → Try with Outlook or Yahoo (see NEW_FEATURES.md)"
echo "  → Temporarily set ENABLE_EMAIL=false to disable"
echo ""
